In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../data/cars.csv")

df.head()

,manufacturer,model,year,mileage,engine,transmission,drivetrain,fuel_type,mpg,exterior_color,interior_color,accidents_or_damage,one_owner,personal_use_only,seller_name,seller_rating,driver_rating,driver_reviews_num,price_drop,price
0,Acura,ILX Hybrid 1.5L,2013,92945.0,"1.5L I-4 i-VTEC variable valve control, engine...",Automatic,Front-wheel Drive,Gasoline,39-38,Black,Parchment,0.0,0.0,0.0,Iconic Coach,NaN,4.4,12.0,300.0,13988.0
1,Acura,ILX Hybrid 1.5L,2013,47645.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Gray,Ebony,1.0,1.0,1.0,Kars Today,NaN,4.4,12.0,NaN,17995.0
2,Acura,ILX Hybrid 1.5L,2013,53422.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Bellanova White Pearl,Ebony,0.0,1.0,1.0,Weiss Toyota of South County,4.3,4.4,12.0,500.0,17000.0
3,Acura,ILX Hybrid 1.5L,2013,117598.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Polished Metal Metallic,NaN,0.0,1.0,1.0,Apple Tree Acura,NaN,4.4,12.0,675.0,14958.0
4,Acura,ILX Hybrid 1.5L,2013,114865.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,NaN,Ebony,1.0,0.0,1.0,Herb Connolly Chevrolet,3.7,4.4,12.0,300.0,14498.0

In [2]:
df.shape

(762091, 20)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 762091 entries, 0 to 762090
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   manufacturer         762091 non-null  str
 1   model                762091 non-null  str
 2   year                 762091 non-null  int64
 3   mileage              761585 non-null  float64
 4   engine               747041 non-null  str
 5   transmission         752187 non-null  str
 6   drivetrain           740529 non-null  str
 7   fuel_type            739164 non-null  str
 8   mpg                  620020 non-null  str
 9   exterior_color       753232 non-null  str
 10  interior_color       705116 non-null  str
 11  accidents_or_damage  737879 non-null  float64
 12  one_owner            730608 non-null  float64
 13  personal_use_only    737239 non-null  float64
 14  seller_name          753498 non-null  str
 15  seller_rating        548118 non-null  float64
 16  driver_rating        730459 non-null  float64
 17  driver_reviews_num   762091 non-null  float64
 18  price_drop           410112 non-null  float64
 19  price                762091 non-null  float64
dtypes: float64(9), int64(1), str(10)
memory usage: 116.3 MB

In [4]:
df.describe(include="all")

,manufacturer,model,year,mileage,engine,transmission,drivetrain,fuel_type,mpg,exterior_color,interior_color,accidents_or_damage,one_owner,personal_use_only,seller_name,seller_rating,driver_rating,driver_reviews_num,price_drop,price
count,762091,762091,762091.000000,7.615850e+05,747041,752187,740529,739164,620020,753232,705116,737879.000000,730608.000000,737239.000000,753498,548118.000000,730459.000000,762091.000000,410112.000000,7.620910e+05
unique,30,12187,NaN,NaN,6903,1313,33,36,865,7681,4679,NaN,NaN,NaN,18254,NaN,NaN,NaN,NaN,NaN
top,Ford,Fusion SE,NaN,NaN,2.0L I4 16V GDI DOHC Turbo,6-Speed Automatic,Front-wheel Drive,Gasoline,19-26,Black,Black,NaN,NaN,NaN,Gateway Classic Cars,NaN,NaN,NaN,NaN,NaN
freq,79526,3172,NaN,NaN,75545,148597,241432,644644,16210,60250,286298,NaN,NaN,NaN,1638,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,2017.791398,5.578169e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.228616,0.561969,0.657212,NaN,4.158568,4.623523,89.550900,1007.467068,3.648898e+04
std,NaN,NaN,5.110532,4.355788e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.419942,0.496145,0.474642,NaN,0.805741,0.276902,115.082266,1375.122208,1.984183e+06
min,NaN,NaN,1915.000000,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,1.000000,1.000000,0.000000,100.000000,1.000000e+00
25%,NaN,NaN,2016.000000,2.328700e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,3.800000,4.500000,14.000000,380.000000,1.958300e+04
50%,NaN,NaN,2019.000000,4.559600e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,1.000000,NaN,4.500000,4.700000,51.000000,642.000000,2.798900e+04
75%,NaN,NaN,2021.000000,7.836500e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,1.000000,NaN,4.700000,4.800000,119.000000,1007.000000,3.948800e+04
max,NaN,NaN,2024.000000,1.119067e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,5.000000,5.000000,1025.000000,170995.000000,1.000000e+09

In [5]:
df.isnull().sum()

manufacturer                0
model                       0
year                        0
mileage                   506
engine                  15050
transmission             9904
drivetrain              21562
fuel_type               22927
mpg                    142071
exterior_color           8859
interior_color          56975
accidents_or_damage     24212
one_owner               31483
personal_use_only       24852
seller_name              8593
seller_rating          213973
driver_rating           31632
driver_reviews_num          0
price_drop             351979
price                       0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(9145)

In [7]:
df["price"].quantile([0, 0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99, 0.999, 1])

0.000    1.000000e+00
0.010    5.999000e+03
0.050    9.995000e+03
0.250    1.958300e+04
0.500    2.798900e+04
0.750    3.948800e+04
0.950    6.884600e+04
0.990    1.099950e+05
0.999    2.399959e+05
1.000    1.000000e+09
Name: price, dtype: float64

In [8]:
df.nlargest(20, "price")[[
    "manufacturer",
    "model",
    "year",
    "mileage",
    "price"
]]

,manufacturer,model,year,mileage,price
108142,Chevrolet,Cobalt LT,2009,85185.0,1.000000e+09
188113,Dodge,Durango Citadel,2018,113207.0,1.000000e+09
188260,Dodge,Durango Citadel,2018,113207.0,1.000000e+09
224571,Ford,Utility Police Interceptor Base,2016,NaN,8.888889e+06
84358,Cadillac,DeVille 77 HOURS ON ENGINES,1963,76.0,4.999999e+06
636956,RAM,ProMaster 3500 High Roof,2017,83000.0,3.490000e+06
613085,Porsche,Carrera GT,2005,780.0,2.250000e+06
609009,Porsche,918 Spyder Base (PDK),2015,2622.0,2.099995e+06
613080,Porsche,Carrera GT,2004,2361.0,1.899999e+06
49078,BMW,750 iL,1996,121043.0,1.750000e+06
613084,Porsche,Carrera GT,2005,9610.0,1.650000e+06
213659,Ford,GT EDITION VIN 002,2018,9.0,1.575000e+06
613079,Porsche,Carrera GT Base (M6),2004,4376.0,1.549991e+06
613081,Porsche,Carrera GT,2005,12996.0,1.499177e+06
613083,Porsche,Carrera GT,2005,5052.0,1.495000e+06
613082,Porsche,Carrera GT Base (M6),2005,10982.0,1.400000e+06
613086,Porsche,Carrera GT Base (M6),2005,11750.0,1.390000e+06
616430,Porsche,911 Turbo 3.6,1994,2370.0,1.350000e+06
213649,Ford,GT,2020,24.0,1.295000e+06
213658,Ford,GT,2019,255.0,1.275000e+06

In [9]:
df[df["price"] <= 1000][[
    "manufacturer",
    "model",
    "year",
    "mileage",
    "price"
]].sort_values("price")

       manufacturer                 model  year   mileage   price
5658          Acura         TLX V6 A-Spec  2018   49603.0     1.0
13850          Audi       A4 2.0T Premium  2014   98881.0     1.0
735177   Volkswagen                 Jetta  2007  133964.0     1.0
660696       Subaru   Legacy 2.5i Limited  2019   31570.0     1.0
584638       Nissan              Versa SV  2021   45288.0   259.0
195371         Ford     EcoSport Titanium  2019   44077.0   289.0
66049         Buick       Enclave Premium  2017  115869.0   299.0
599832       Nissan             Murano SV  2018  120524.0   299.0
73551         Buick        Encore Essence  2019  115608.0   299.0
600748       Nissan             Murano SV  2018  120524.0   299.0
736374   Volkswagen               Jetta S  2019  120092.0   319.0
680496       Toyota               C-HR LE  2019  104481.0   399.0
553053   Mitsubishi    Outlander Sport SE  2021   56509.0   399.0
165324        Dodge      Grand Caravan GT  2019   72860.0   399.0
162360     Chrysler    Pacifica Touring L  2020   55240.0   399.0
165200        Dodge      Grand Caravan GT  2019   72860.0   399.0
566508       Nissan             Maxima SE  2001  157000.0   500.0
639501       Subaru        Ascent Limited  2022    2277.0   595.0
165031        Dodge            Caravan SE  1997  201611.0   695.0
760485        Volvo                V70 T5  1998  193695.0   695.0
709556       Toyota         Prius Touring  2008  185000.0   700.0
567062       Nissan           Cube 1.8 SL  2009       NaN   750.0
247974         Ford                Ranger  1989  200028.0   850.0
249314         Ford            Ranger STX  1993  160025.0   850.0
250581         Ford             Taurus SE  2002  214207.0   895.0
424110          Kia            Sorento LX  2007  251072.0   900.0
176129        Dodge            Avenger SE  2008  162222.0   975.0
99988     Chevrolet         Uplander Base  2005  148164.0   985.0
555745   Mitsubishi                Lancer  2006  255000.0   994.0
127081    Chevrolet           Cavalier LS  2002  153610.0   995.0
170656        Dodge              Ram 1500  2002  305138.0   995.0
185691        Dodge           Durango SLT  2005  230327.0   995.0
565918       Nissan             Maxima SE  2002  272284.0   995.0
586294       Nissan           Versa 1.8 S  2012  173373.0   995.0
107511    Chevrolet         Impala Police  2008  102698.0   999.0
502525        Mazda        Mazda3 s Sport  2010  128309.0   999.0
488230      Lincoln              MKZ Base  2011  166093.0   999.0
70592         Buick           Lucerne CXL  2008   92272.0   999.0
179562        Dodge               Dart SE  2013  122712.0   999.0
560384       Nissan  Frontier XE Crew Cab  2003  168317.0  1000.0
601831       Nissan          Quest 3.5 SL  2008  189354.0  1000.0
761264        Volvo               S60 2.4  2002  141000.0  1000.0

In [10]:
df[df["year"] < 1980][[
    "manufacturer",
    "model",
    "year",
    "mileage",
    "price"
]].sort_values("year")

       manufacturer                   model  year  mileage    price
269791         Ford                 Model T  1915      0.0  26000.0
269785         Ford         Model T Touring  1915      0.0  33000.0
269783         Ford        Model T Runabout  1917      0.0  22500.0
77047         Buick            Model H Base  1919  10240.0  76000.0
269787         Ford                 Model T  1923      0.0  24995.0
...             ...                     ...   ...      ...      ...
741497   Volkswagen  Beetle (Pre-1980) Base  1979  81628.0  25000.0
741498   Volkswagen       Beetle (Pre-1980)  1979   6530.0  32995.0
395126         Jeep               CJ-7 Base  1979  18130.0  40000.0
242222         Ford    Ranchero GT Brougham  1979  15132.0  28000.0
741526   Volkswagen       Beetle (Pre-1980)  1979  32796.0  34900.0

[2253 rows x 5 columns]

In [11]:
df["mileage"].quantile([0, 0.5, 0.9, 0.95, 0.99, 0.999, 1])

0.000          0.000
0.500      45596.000
0.900     114329.600
0.950     138774.000
0.990     193606.480
0.999     275044.824
1.000    1119067.000
Name: mileage, dtype: float64

In [12]:
df.nlargest(20, "mileage")[[
    "manufacturer",
    "model",
    "year",
    "mileage",
    "price"
]]

,manufacturer,model,year,mileage,price
756847,Volvo,XC70 3.2L,2010,1119067.0,16997.0
76422,Buick,Century Custom,1998,999999.0,1995.0
494409,Lincoln,Continental,1967,999999.0,22900.0
511961,Mercedes-Benz,GLK-Class GLK 350,2011,999999.0,13995.0
617503,Porsche,356 A,1959,974302.0,179500.0
319941,Honda,Civic LX,2013,938032.0,14816.0
522994,Mercedes-Benz,E-Class E 350 4MATIC,2021,915383.0,53539.0
136180,Chevrolet,Silverado 3500 LTZ,2013,777698.0,16999.0
669643,Toyota,Camry LE,2020,769938.0,21825.0
229883,Ford,F-350 Lariat Super Duty,2014,763474.0,23995.0
302334,Honda,Pilot LX,2020,754680.0,20499.0
157346,Chrysler,Voyager LXI,2021,724500.0,20491.0
481170,Lexus,IS 250 Base,2014,680094.0,21700.0
4896,Acura,RDX,2020,668131.0,33688.0
169278,Dodge,Sprinter,2005,662110.0,8995.0
121155,Chevrolet,Trax LS,2018,653132.0,15287.0
456962,Land Rover,Range Rover Sport Supercharged SE,2016,644736.0,34777.0
298512,GMC,Sierra 2500 SLT,2010,638693.0,5000.0
220225,Ford,Transit-350 XL,2016,620637.0,39990.0
531797,Mercedes-Benz,C-Class C 300 4MATIC,2019,566517.0,35955.0

In [13]:
df[["manufacturer", "model", "year"]].value_counts().head(20)

manufacturer   model                  year
Mercedes-Benz  GLC 300 Base 4MATIC    2022    1443
Kia            Optima LX              2020     962
Ford           Explorer XLT           2020     918
Kia            Forte LXS              2021     915
               Sportage LX            2020     905
Ford           Fusion SE              2020     894
INFINITI       QX60 Luxe              2020     874
Cadillac       XT5 Luxury             2019     873
Buick          Encore Preferred       2019     860
Nissan         Sentra SV              2019     808
Ford           Transit-250 Base       2020     803
Kia            Forte LXS              2020     780
Hyundai        Elantra SEL            2020     769
Toyota         Corolla LE             2021     756
GMC            Terrain SLE            2020     739
Toyota         Corolla LE             2020     737
Chevrolet      Malibu LT              2020     726
Volkswagen     Jetta 1.4T S           2019     705
Chevrolet      Trax LT                2020     663
Ford           Bronco Sport Big Bend  2021     662
Name: count, dtype: int64

In [14]:
df[df["price"] < 5000][[
    "manufacturer",
    "model",
    "year",
    "mileage",
    "price"
]].sort_values("price").head(50)

       manufacturer                  model  year   mileage   price
735177   Volkswagen                  Jetta  2007  133964.0     1.0
5658          Acura          TLX V6 A-Spec  2018   49603.0     1.0
13850          Audi        A4 2.0T Premium  2014   98881.0     1.0
660696       Subaru    Legacy 2.5i Limited  2019   31570.0     1.0
584638       Nissan               Versa SV  2021   45288.0   259.0
195371         Ford      EcoSport Titanium  2019   44077.0   289.0
66049         Buick        Enclave Premium  2017  115869.0   299.0
600748       Nissan              Murano SV  2018  120524.0   299.0
599832       Nissan              Murano SV  2018  120524.0   299.0
73551         Buick         Encore Essence  2019  115608.0   299.0
736374   Volkswagen                Jetta S  2019  120092.0   319.0
553053   Mitsubishi     Outlander Sport SE  2021   56509.0   399.0
162360     Chrysler     Pacifica Touring L  2020   55240.0   399.0
165200        Dodge       Grand Caravan GT  2019   72860.0   399.0
165324        Dodge       Grand Caravan GT  2019   72860.0   399.0
680496       Toyota                C-HR LE  2019  104481.0   399.0
566508       Nissan              Maxima SE  2001  157000.0   500.0
639501       Subaru         Ascent Limited  2022    2277.0   595.0
165031        Dodge             Caravan SE  1997  201611.0   695.0
760485        Volvo                 V70 T5  1998  193695.0   695.0
709556       Toyota          Prius Touring  2008  185000.0   700.0
567062       Nissan            Cube 1.8 SL  2009       NaN   750.0
249314         Ford             Ranger STX  1993  160025.0   850.0
247974         Ford                 Ranger  1989  200028.0   850.0
250581         Ford              Taurus SE  2002  214207.0   895.0
424110          Kia             Sorento LX  2007  251072.0   900.0
176129        Dodge             Avenger SE  2008  162222.0   975.0
99988     Chevrolet          Uplander Base  2005  148164.0   985.0
555745   Mitsubishi                 Lancer  2006  255000.0   994.0
127081    Chevrolet            Cavalier LS  2002  153610.0   995.0
170656        Dodge               Ram 1500  2002  305138.0   995.0
565918       Nissan              Maxima SE  2002  272284.0   995.0
586294       Nissan            Versa 1.8 S  2012  173373.0   995.0
185691        Dodge            Durango SLT  2005  230327.0   995.0
488230      Lincoln               MKZ Base  2011  166093.0   999.0
70592         Buick            Lucerne CXL  2008   92272.0   999.0
502525        Mazda         Mazda3 s Sport  2010  128309.0   999.0
107511    Chevrolet          Impala Police  2008  102698.0   999.0
179562        Dodge                Dart SE  2013  122712.0   999.0
601831       Nissan           Quest 3.5 SL  2008  189354.0  1000.0
560384       Nissan   Frontier XE Crew Cab  2003  168317.0  1000.0
761264        Volvo                S60 2.4  2002  141000.0  1000.0
164997     Chrysler     PT Cruiser Touring  2004  171422.0  1100.0
107920    Chevrolet            Impala Base  2004  281965.0  1100.0
734495   Volkswagen          Jetta GLS VR6  2000  170199.0  1195.0
760504        Volvo                 V70 GT  1998  220974.0  1195.0
760476        Volvo                V70 2.4  2004  177178.0  1195.0
180640        Dodge           Ram Van 1500  2001  208290.0  1195.0
268749         Ford                   E150  1994       1.0  1200.0
390461         Jeep  Grand Cherokee Laredo  2004  119784.0  1200.0

In [15]:
df[df["price"] > 500000][[
    "manufacturer",
    "model",
    "year",
    "mileage",
    "price"
]].sort_values("price", ascending=False)

,manufacturer,model,year,mileage,price
108142,Chevrolet,Cobalt LT,2009,85185.0,1.000000e+09
188260,Dodge,Durango Citadel,2018,113207.0,1.000000e+09
188113,Dodge,Durango Citadel,2018,113207.0,1.000000e+09
224571,Ford,Utility Police Interceptor Base,2016,NaN,8.888889e+06
84358,Cadillac,DeVille 77 HOURS ON ENGINES,1963,76.0,4.999999e+06
636956,RAM,ProMaster 3500 High Roof,2017,83000.0,3.490000e+06
613085,Porsche,Carrera GT,2005,780.0,2.250000e+06
609009,Porsche,918 Spyder Base (PDK),2015,2622.0,2.099995e+06
613080,Porsche,Carrera GT,2004,2361.0,1.899999e+06
49078,BMW,750 iL,1996,121043.0,1.750000e+06
613084,Porsche,Carrera GT,2005,9610.0,1.650000e+06
213659,Ford,GT EDITION VIN 002,2018,9.0,1.575000e+06
613079,Porsche,Carrera GT Base (M6),2004,4376.0,1.549991e+06
613081,Porsche,Carrera GT,2005,12996.0,1.499177e+06
613083,Porsche,Carrera GT,2005,5052.0,1.495000e+06
613082,Porsche,Carrera GT Base (M6),2005,10982.0,1.400000e+06
613086,Porsche,Carrera GT Base (M6),2005,11750.0,1.390000e+06
616430,Porsche,911 Turbo 3.6,1994,2370.0,1.350000e+06
213649,Ford,GT,2020,24.0,1.295000e+06
213658,Ford,GT,2019,255.0,1.275000e+06
213641,Ford,GT,2019,619.0,1.269000e+06
615573,Porsche,911 Turbo S,2019,134.0,1.200888e+06
528281,Mercedes-Benz,G-Class 650,2018,100.0,1.199990e+06
213647,Ford,GT,2019,3215.0,1.190000e+06
540908,Mercedes-Benz,SLR McLaren,2009,650.0,1.150000e+06
213644,Ford,GT,2020,1054.0,1.149900e+06
244466,Ford,Sedan Police Interceptor Base,2017,78920.0,1.111111e+06
91190,Cadillac,DTS,2006,158021.0,1.111111e+06
615422,Porsche,911 Turbo S,1997,1779.0,8.999750e+05
613087,Porsche,Carrera GT,2005,8342.0,8.499000e+05
196582,Ford,Mustang Shelby GT Shelby GT,1967,NaN,8.290000e+05
616478,Porsche,911 GT2 RS,2019,2185.0,7.950000e+05
616115,Porsche,911 GT2 RS,2019,2.0,7.899000e+05
131403,Chevrolet,Blazer Formula 1 Car,2022,1.0,7.500000e+05
540909,Mercedes-Benz,SLR McLaren,2006,461.0,7.499500e+05
517360,Mercedes-Benz,AMG GT C,2021,38.0,7.477000e+05
615264,Porsche,911 GT3 RS 4.0,2011,475.0,7.400000e+05
616031,Porsche,911 Sport Classic,2023,100.0,6.990000e+05
213660,Ford,GT Base,2006,6492.0,6.399500e+05
614808,Porsche,911 Turbo S,1997,34782.0,6.149000e+05
616582,Porsche,911 GT3 RS 4.0,2011,12660.0,5.859900e+05
541508,Mercedes-Benz,AMG G 63 Base,2021,1450.0,5.590000e+05
616253,Porsche,911 Turbo 3.6,1997,1.0,5.509900e+05
616032,Porsche,911 GT2 RS,2018,14.0,5.500000e+05
213664,Ford,GT Base,2005,2804.0,5.500000e+05
540906,Mercedes-Benz,SLR McLaren,2006,3302.0,5.499500e+05
213645,Ford,GT Base,2006,261.0,5.499000e+05
492644,Lincoln,Nautilus Reserve,2022,11878.0,5.491120e+05
617296,Porsche,911 Carrera,1997,34485.0,5.450000e+05
213639,Ford,GT Base,2005,2517.0,5.350000e+05
213652,Ford,GT Base,2006,266.0,5.299960e+05
540900,Mercedes-Benz,SLR McLaren,2006,5770.0,5.299500e+05
541485,Mercedes-Benz,AMG G 63 4x4 Squared,2022,176.0,5.150000e+05
614750,Porsche,911 R,2016,9481.0,5.119110e+05
615526,Porsche,911 GT2 RS,2018,647.0,5.100000e+05
615878,Porsche,911 R,2016,1266.0,5.070000e+05
617135,Porsche,911 R,2016,1266.0,5.070000e+05

In [16]:
df[df.duplicated(keep=False)].sort_values(
    ["manufacturer", "model", "year"]
).head(30)

,manufacturer,model,year,mileage,engine,transmission,drivetrain,fuel_type,mpg,exterior_color,interior_color,accidents_or_damage,one_owner,personal_use_only,seller_name,seller_rating,driver_rating,driver_reviews_num,price_drop,price
405,Acura,ILX,2017,56482.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,25-35,Lunar Silver Metallic,Ebony,0.0,0.0,1.0,Where Luxury Meets,4.2,4.7,38.0,NaN,16705.0
432,Acura,ILX,2017,56482.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,25-35,Lunar Silver Metallic,Ebony,0.0,0.0,1.0,Where Luxury Meets,4.2,4.7,38.0,NaN,16705.0
763,Acura,ILX,2018,50895.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,25-35,Red,Parchment,1.0,0.0,1.0,Car2Sell,4.7,4.6,20.0,400.0,16900.0
861,Acura,ILX,2018,50895.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,25-35,Red,Parchment,1.0,0.0,1.0,Car2Sell,4.7,4.6,20.0,400.0,16900.0
898,Acura,ILX,2018,18573.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,25-35,Gray,Ebony,0.0,1.0,1.0,The Internet Car Lot,3.8,4.6,20.0,NaN,18995.0
981,Acura,ILX,2018,18573.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,25-35,Gray,Ebony,0.0,1.0,1.0,The Internet Car Lot,3.8,4.6,20.0,NaN,18995.0
529,Acura,ILX,2022,7339.0,NaN,8 Speed Dual-Clutch,NaN,Gasoline,NaN,Lunar Silver Metallic,Ebony,NaN,NaN,NaN,Walker Acura,NaN,NaN,0.0,NaN,32975.0
1052,Acura,ILX,2022,7339.0,NaN,8 Speed Dual-Clutch,NaN,Gasoline,NaN,Lunar Silver Metallic,Ebony,NaN,NaN,NaN,Walker Acura,NaN,NaN,0.0,NaN,32975.0
902,Acura,ILX 2.0L,2015,58490.0,2.0L I4 16V MPFI SOHC,5-Speed Automatic,Front-wheel Drive,Gasoline,24-35,Black,NaN,0.0,1.0,1.0,Unique Auto Center,NaN,4.7,23.0,NaN,17995.0
989,Acura,ILX 2.0L,2015,58490.0,2.0L I4 16V MPFI SOHC,5-Speed Automatic,Front-wheel Drive,Gasoline,24-35,Black,NaN,0.0,1.0,1.0,Unique Auto Center,NaN,4.7,23.0,NaN,17995.0
635,Acura,ILX 2.0L Technology,2013,90667.0,2.0L I4 16V MPFI SOHC,Automatic,Front-wheel Drive,Gasoline,NaN,Gray,Ebony,0.0,0.0,1.0,M Auto Group,NaN,4.6,47.0,510.0,12985.0
655,Acura,ILX 2.0L Technology,2013,82370.0,2.0L I4 16V MPFI SOHC,Automatic,Front-wheel Drive,Gasoline,NaN,Amber Brownstone Metallic,Ebony,1.0,0.0,1.0,Deluxe Auto Dealer,2.0,4.6,47.0,1000.0,10995.0
683,Acura,ILX 2.0L Technology,2013,82370.0,2.0L I4 16V MPFI SOHC,Automatic,Front-wheel Drive,Gasoline,NaN,Amber Brownstone Metallic,Ebony,1.0,0.0,1.0,Deluxe Auto Dealer,2.0,4.6,47.0,1000.0,10995.0
730,Acura,ILX 2.0L Technology,2013,90667.0,2.0L I4 16V MPFI SOHC,Automatic,Front-wheel Drive,Gasoline,NaN,Gray,Ebony,0.0,0.0,1.0,M Auto Group,NaN,4.6,47.0,510.0,12985.0
822,Acura,ILX 2.0L w/Premium Package,2013,59121.0,2.0L I4 16V MPFI SOHC,5-Speed Automatic,Front-wheel Drive,Gasoline,NaN,Diamond White Pearl,Ebony,1.0,0.0,0.0,Serra Honda Grandville,4.9,4.6,47.0,250.0,16300.0
880,Acura,ILX 2.0L w/Premium Package,2013,59121.0,2.0L I4 16V MPFI SOHC,5-Speed Automatic,Front-wheel Drive,Gasoline,NaN,Diamond White Pearl,Ebony,1.0,0.0,0.0,Serra Honda Grandville,4.9,4.6,47.0,250.0,16300.0
278,Acura,ILX 2.0L w/Premium Package,2015,109327.0,2.0L I4 16V MPFI SOHC,5-Speed Automatic,Front-wheel Drive,Gasoline,NaN,Gray,NaN,1.0,0.0,1.0,Mercedes-Benz of Rocklin,4.5,4.7,23.0,299.0,15891.0
322,Acura,ILX 2.0L w/Premium Package,2015,109327.0,2.0L I4 16V MPFI SOHC,5-Speed Automatic,Front-wheel Drive,Gasoline,NaN,Gray,NaN,1.0,0.0,1.0,Mercedes-Benz of Rocklin,4.5,4.7,23.0,299.0,15891.0
910,Acura,ILX 2.4L,2016,77237.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,25-36,Black,Ebony,0.0,0.0,1.0,Oakley Auto World,4.9,4.4,44.0,NaN,20000.0
932,Acura,ILX 2.4L,2016,77237.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,25-36,Black,Ebony,0.0,0.0,1.0,Oakley Auto World,4.9,4.4,44.0,NaN,20000.0
149,Acura,ILX 2.4L w/Premium Package,2015,81883.0,2.4L I4 16V MPFI DOHC,6-Speed Manual,Front-wheel Drive,Gasoline,22-31,Black,Ebony,1.0,0.0,1.0,Elk Grove Subaru,4.9,4.7,23.0,1000.0,15988.0
179,Acura,ILX 2.4L w/Premium Package,2015,81883.0,2.4L I4 16V MPFI DOHC,6-Speed Manual,Front-wheel Drive,Gasoline,22-31,Black,Ebony,1.0,0.0,1.0,Elk Grove Subaru,4.9,4.7,23.0,1000.0,15988.0
140,Acura,ILX Base,2018,29997.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,25-35,Gray,Ebony,0.0,1.0,1.0,Costa Mesa Buick GMC,NaN,4.6,20.0,800.0,23988.0
161,Acura,ILX Base,2018,29997.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,25-35,Gray,Ebony,0.0,1.0,1.0,Costa Mesa Buick GMC,NaN,4.6,20.0,800.0,23988.0
269,Acura,ILX Base,2020,0.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,24-34,Black,NaN,0.0,1.0,1.0,Acura of Valley Stream,4.6,4.6,17.0,NaN,23995.0
299,Acura,ILX Base,2020,0.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,24-34,Black,NaN,0.0,1.0,1.0,Acura of Valley Stream,4.6,4.6,17.0,NaN,23995.0
243,Acura,ILX Base,2021,18375.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,24-34,Performance Red Pearl,Ebony,0.0,1.0,1.0,Ed Napleton Acura Kia,3.3,4.9,3.0,1500.0,24995.0
345,Acura,ILX Base,2021,18375.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,24-34,Performance Red Pearl,Ebony,0.0,1.0,1.0,Ed Napleton Acura Kia,3.3,4.9,3.0,1500.0,24995.0
750,Acura,ILX Base,2022,14336.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,24-34,White,Ebony,0.0,1.0,1.0,Autopia Motorcars Inc,2.0,NaN,0.0,NaN,26999.0
848,Acura,ILX Base,2022,14336.0,2.4L I4 16V GDI DOHC,8-Speed Automatic with Auto-Shift,Front-wheel Drive,Gasoline,24-34,White,Ebony,0.0,1.0,1.0,Autopia Motorcars Inc,2.0,NaN,0.0,NaN,26999.0

In [17]:
df.groupby(
    ["manufacturer", "model", "year"]
).size().sort_values(ascending=False).head(30)

manufacturer   model                   year
Mercedes-Benz  GLC 300 Base 4MATIC     2022    1443
Kia            Optima LX               2020     962
Ford           Explorer XLT            2020     918
Kia            Forte LXS               2021     915
               Sportage LX             2020     905
Ford           Fusion SE               2020     894
INFINITI       QX60 Luxe               2020     874
Cadillac       XT5 Luxury              2019     873
Buick          Encore Preferred        2019     860
Nissan         Sentra SV               2019     808
Ford           Transit-250 Base        2020     803
Kia            Forte LXS               2020     780
Hyundai        Elantra SEL             2020     769
Toyota         Corolla LE              2021     756
GMC            Terrain SLE             2020     739
Toyota         Corolla LE              2020     737
Chevrolet      Malibu LT               2020     726
Volkswagen     Jetta 1.4T S            2019     705
Chevrolet      Trax LT                 2020     663
Ford           Bronco Sport Big Bend   2021     662
Jeep           Cherokee Limited        2019     659
Mercedes-Benz  GLE 350 Base 4MATIC     2020     654
Ford           Ranger XLT              2019     654
               Edge SEL                2020     633
Jeep           Gladiator Rubicon       2020     632
Nissan         Rogue Sport S           2020     629
Ford           Expedition Max Limited  2021     615
Volkswagen     Taos 1.5T SE            2022     609
GMC            Terrain SLT             2020     608
Nissan         Rogue SV                2020     599
dtype: int64

In [18]:
print("Rows:", len(df))

print("Price <= 1000:", (df["price"] <= 1000).sum())
print("Price >= 1,000,000:", (df["price"] >= 1_000_000).sum())

print("Mileage == 999999:", (df["mileage"] == 999999).sum())
print("Mileage > 500000:", (df["mileage"] > 500_000).sum())

print("Exact duplicates:", df.duplicated().sum())

Rows: 762091
Price <= 1000: 42
Price >= 1,000,000: 28
Mileage == 999999: 3
Mileage > 500000: 26
Exact duplicates: 9145

In [19]:
df[df["price"] >= 1_000_000][
    ["manufacturer", "model", "year", "mileage", "price"]
].sort_values("price", ascending=False).tail(30)

,manufacturer,model,year,mileage,price
108142,Chevrolet,Cobalt LT,2009,85185.0,1.000000e+09
188113,Dodge,Durango Citadel,2018,113207.0,1.000000e+09
188260,Dodge,Durango Citadel,2018,113207.0,1.000000e+09
224571,Ford,Utility Police Interceptor Base,2016,NaN,8.888889e+06
84358,Cadillac,DeVille 77 HOURS ON ENGINES,1963,76.0,4.999999e+06
636956,RAM,ProMaster 3500 High Roof,2017,83000.0,3.490000e+06
613085,Porsche,Carrera GT,2005,780.0,2.250000e+06
609009,Porsche,918 Spyder Base (PDK),2015,2622.0,2.099995e+06
613080,Porsche,Carrera GT,2004,2361.0,1.899999e+06
49078,BMW,750 iL,1996,121043.0,1.750000e+06
613084,Porsche,Carrera GT,2005,9610.0,1.650000e+06
213659,Ford,GT EDITION VIN 002,2018,9.0,1.575000e+06
613079,Porsche,Carrera GT Base (M6),2004,4376.0,1.549991e+06
613081,Porsche,Carrera GT,2005,12996.0,1.499177e+06
613083,Porsche,Carrera GT,2005,5052.0,1.495000e+06
613082,Porsche,Carrera GT Base (M6),2005,10982.0,1.400000e+06
613086,Porsche,Carrera GT Base (M6),2005,11750.0,1.390000e+06
616430,Porsche,911 Turbo 3.6,1994,2370.0,1.350000e+06
213649,Ford,GT,2020,24.0,1.295000e+06
213658,Ford,GT,2019,255.0,1.275000e+06
213641,Ford,GT,2019,619.0,1.269000e+06
615573,Porsche,911 Turbo S,2019,134.0,1.200888e+06
528281,Mercedes-Benz,G-Class 650,2018,100.0,1.199990e+06
213647,Ford,GT,2019,3215.0,1.190000e+06
540908,Mercedes-Benz,SLR McLaren,2009,650.0,1.150000e+06
213644,Ford,GT,2020,1054.0,1.149900e+06
91190,Cadillac,DTS,2006,158021.0,1.111111e+06
244466,Ford,Sedan Police Interceptor Base,2017,78920.0,1.111111e+06

In [20]:
df_clean = df.copy()

# Remove exact duplicates
df_clean = df_clean.drop_duplicates()

# Remove clearly invalid prices
df_clean = df_clean[
    (df_clean["price"] > 1000) &
    (df_clean["price"] < 1_000_000)
]

# Replace clearly invalid mileage with missing values
df_clean.loc[df_clean["mileage"] > 500_000, "mileage"] = np.nan

print("Original rows:", len(df))
print("Cleaned rows:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))

print("\nRemaining missing values:")
print(df_clean.isnull().sum())

Original rows: 762091
Cleaned rows: 752879
Rows removed: 9212

Remaining missing values:
manufacturer                0
model                       0
year                        0
mileage                   502
engine                  14454
transmission             9477
drivetrain              20887
fuel_type               22149
mpg                    139872
exterior_color           8718
interior_color          55849
accidents_or_damage     23649
one_owner               30758
personal_use_only       24285
seller_name              8490
seller_rating          211476
driver_rating           31270
driver_reviews_num          0
price_drop             346667
price                       0
dtype: int64